name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.12", "3.13-dev"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install poetry
        run: |
          pipx install poetry
          poetry config virtualenvs.create true --local
          poetry config virtualenvs.in-project true --local

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - name: check
        run: poetry check

      - name: install
        run: poetry install --sync

      - name: codespell
        run: poetry run codespell .

      - name: codespell
        run: poetry run ruff check --output-format=github

      - name: basedpyright
        run: poetry run basedpyright

      - name: basedpyright --verifytypes
        run: poetry run basedpyright --ignoreexternal --verifytypes exports

      - name: pytest
        run: poetry run pytest
